"""Task definition, statuses, execution policies, and contracts."""
from __future__ import annotations
from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from .condition import BranchCondition


class TaskType(str, Enum):
    """Permitted analytical task classifications."""
    INGESTION = "ingestion"
    PROFILING = "profiling"
    VALIDATION = "validation"
    CLEANING = "cleaning"
    EDA = "eda"
    STATISTICAL_ANALYSIS = "statistical_analysis"
    ANOMALY_DETECTION = "anomaly_detection"
    SEGMENTATION = "segmentation"
    MACHINE_LEARNING = "machine_learning"
    ROOT_CAUSE_ANALYSIS = "root_cause_analysis"
    VISUALIZATION = "visualization"
    RECOMMENDATION = "recommendation"
    REPORTING = "reporting"
    HUMAN_REVIEW = "human_review"


class TaskStatus(str, Enum):
    """Lifecycle states of a task in the execution graph."""
    PENDING = "pending"
    READY = "ready"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"
    PAUSED = "paused"
    ESCALATED = "escalated"


class FailurePolicy(str, Enum):
    """Policy governing unhandled exceptions or tool errors."""
    RETRY = "retry"
    SKIP = "skip"
    FALLBACK = "fallback"
    PAUSE = "pause"
    ESCALATE = "escalate"
    TERMINATE = "terminate"


class RetryPolicy(BaseModel):
    """Execution retry parameters."""
    max_retries: int = Field(3, ge=0, le=10, description="Max attempts before applying failure policy")
    backoff_factor: float = Field(2.0, ge=1.0, description="Exponential backoff multiplier")
    initial_delay_sec: float = Field(1.0, ge=0.0, description="Initial delay in seconds")
    fallback_task_id: Optional[str] = Field(None, description="Alternative task to execute upon exhausting retries")


class TaskPriority(str, Enum):
    """Scheduling priority level."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class KnowledgeRetrievalSpec(BaseModel):
    """Explicit reference to Knowledge Engineer retrieve_knowledge contract."""
    query: str = Field(..., description="Query sent to Knowledge Base")
    category: Optional[str] = Field(None, description="Optional KnowledgeCategory filter")
    subcategory: Optional[str] = Field(None, description="Optional subcategory filter")
    top_k: int = Field(3, ge=1, le=10, description="Top results requested")


class Task(BaseModel):
    """Discrete, deterministic executable analytical task."""
    task_id: str = Field(..., description="Unique deterministic identifier e.g. T001")
    name: str = Field(..., min_length=2, description="Short human-readable task title")
    description: str = Field(..., min_length=5, description="Clear description of analytical operation")
    task_type: TaskType = Field(..., description="Taxonomy classification")
    tool: str = Field(..., min_length=2, description="Contractual tool name invoked by Agent")
    dependencies: List[str] = Field(default_factory=list, description="List of parent task_ids required before execution")
    required_inputs: List[str] = Field(default_factory=list, description="Required artifacts or variables")
    expected_outputs: List[str] = Field(default_factory=list, description="Artifacts or metrics generated by task")
    conditions: List[BranchCondition] = Field(default_factory=list, description="Branch conditions evaluated post-execution")
    failure_policy: FailurePolicy = Field(FailurePolicy.RETRY, description="Error handling policy")
    retry_policy: RetryPolicy = Field(default_factory=RetryPolicy, description="Retry configuration")
    priority: TaskPriority = Field(TaskPriority.MEDIUM, description="Task execution priority")
    status: TaskStatus = Field(TaskStatus.PENDING, description="Initial lifecycle state")
    knowledge_retrieval: Optional[KnowledgeRetrievalSpec] = Field(None, description="Referenced Knowledge Engineer tool contract")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Custom task parameters and configuration")
