"""Root Workflow Graph schema and serialization utilities."""
from __future__ import annotations
import json
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from .task import Task
from .condition import BranchCondition
from .escalation import EscalationRule


class WorkflowInput(BaseModel):
    """Input parameters supplied to initiate a workflow run."""
    dataset_name: str = Field(..., description="Dataset or table reference identifier")
    goal: str = Field(..., description="High-level analytical user goal")
    constraints: Dict[str, Any] = Field(default_factory=dict, description="Execution constraints or parameters")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Supplemental metadata")


class WorkflowOutput(BaseModel):
    """Expected final artifacts generated by the workflow."""
    summary: str = Field(..., description="Summary of workflow findings")
    artifacts: List[str] = Field(default_factory=list, description="Paths or keys to generated output files")
    terminal_task_results: Dict[str, Any] = Field(default_factory=dict, description="Outputs from terminal nodes")


class Workflow(BaseModel):
    """Complete, executable analytical task graph."""
    workflow_id: str = Field(..., description="Unique workflow identifier e.g. WF-REVENUE-001")
    name: str = Field(..., min_length=3, description="Descriptive workflow title")
    version: str = Field("1.0", description="Semantic version string")
    goal: str = Field(..., min_length=5, description="High-level analytical objective")
    entry_task: str = Field(..., description="Root task ID where execution commences")
    terminal_tasks: List[str] = Field(..., min_length=1, description="Leaf task IDs representing completion")
    tasks: List[Task] = Field(..., min_length=1, description="Full collection of task nodes")
    escalation_rules: List[EscalationRule] = Field(default_factory=list, description="Global escalation policies")
    global_conditions: List[BranchCondition] = Field(default_factory=list, description="Global branch policies")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Workflow metadata and provenance")

    def get_task(self, task_id: str) -> Optional[Task]:
        """Retrieve task by task_id."""
        for t in self.tasks:
            if t.task_id == task_id:
                return t
        return None

    def get_successors(self, task_id: str) -> List[Task]:
        """Retrieve all child tasks that depend directly on this task_id."""
        return [t for t in self.tasks if task_id in t.dependencies]

    def get_predecessors(self, task_id: str) -> List[Task]:
        """Retrieve all parent tasks that this task depends on."""
        task = self.get_task(task_id)
        if not task:
            return []
        pred_map = {t.task_id: t for t in self.tasks}
        return [pred_map[dep] for dep in task.dependencies if dep in pred_map]

    def to_dict(self) -> Dict[str, Any]:
        """Serialize workflow to standard Python dictionary."""
        return self.model_dump()

    def to_json(self, indent: int = 2) -> str:
        """Serialize workflow to formatted JSON string."""
        return self.model_dump_json(indent=indent)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> Workflow:
        """Instantiate Workflow from dictionary."""
        return cls(**data)

    @classmethod
    def from_json(cls, json_str: str) -> Workflow:
        """Instantiate Workflow from JSON string."""
        return cls(**json.loads(json_str))
