"""
Inference Engine for Stage 1 ML Candidate V4.
Role: Integration Engineer.

Responsibilities:
- Dynamically loads frozen V4 artifacts via repository-relative paths.
- Reuses existing FeatureEngineer and PreprocessingArtifactManager directly from ml/src.
- Preserves the frozen V4 model and conservative decision rule W = [1.0, 1.05, 1.05].
- Never retrains or modifies model parameters.
"""

import os
import sys
import json
from typing import Dict, Any, List, Union, Optional
import numpy as np
import pandas as pd
import joblib

# Ensure stage-1-ml/ml/src is accessible for FeatureEngineer, PreprocessingArtifactManager, and utils
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
ML_SRC_DIR = os.path.abspath(os.path.join(CURRENT_DIR, "..", "..", "ml", "src"))
if ML_SRC_DIR not in sys.path:
    sys.path.insert(0, ML_SRC_DIR)

from feature_engineering import FeatureEngineer
from preprocessing import PreprocessingArtifactManager
from utils import ThresholdAdjustedClassifier

# Default relative paths (overrideable via environment variables)
DEFAULT_MODEL_PATH = os.getenv(
    "V4_MODEL_PATH",
    os.path.abspath(os.path.join(CURRENT_DIR, "..", "..", "ml", "models", "best_model", "model.joblib"))
)
DEFAULT_PREPROC_PATH = os.getenv(
    "V4_PREPROC_PATH",
    os.path.abspath(os.path.join(CURRENT_DIR, "..", "..", "ml", "artifacts", "preprocessor", "preprocessor.joblib"))
)
DEFAULT_ENCODERS_PATH = os.getenv(
    "V4_ENCODERS_PATH",
    os.path.abspath(os.path.join(CURRENT_DIR, "..", "..", "ml", "artifacts", "encoders", "target_mapping.json"))
)
DEFAULT_CONFIG_PATH = os.getenv(
    "V4_CONFIG_PATH",
    os.path.abspath(os.path.join(CURRENT_DIR, "..", "..", "ml", "results", "v4_candidate_config.json"))
)

DISCLAIMER_TEXT = (
    "This prediction is generated by a research decision-support prototype "
    "and does not constitute a clinical diagnosis or treatment recommendation."
)


class V4InferenceEngine:
    """
    Production-grade inference engine encapsulating the frozen Stage 1 Candidate V4 model.
    """
    def __init__(
        self,
        model_path: Optional[str] = None,
        preproc_path: Optional[str] = None,
        encoders_path: Optional[str] = None,
        config_path: Optional[str] = None
    ):
        self.model_path = os.path.abspath(model_path or DEFAULT_MODEL_PATH)
        self.preproc_path = os.path.abspath(preproc_path or DEFAULT_PREPROC_PATH)
        self.encoders_path = os.path.abspath(encoders_path or DEFAULT_ENCODERS_PATH)
        self.config_path = os.path.abspath(config_path or DEFAULT_CONFIG_PATH)
        
        self.model = None
        self.preprocessor = None
        self.target_mapping = None
        self.reverse_mapping = None
        self.feature_engineer = None
        self.model_version = "V4"
        
        self.load_artifacts()

    def load_artifacts(self) -> None:
        """
        Loads all frozen V4 artifacts from disk. Raises FileNotFoundError if any artifact is missing.
        """
        if not os.path.exists(self.model_path):
            raise FileNotFoundError(f"V4 Model artifact not found at: {self.model_path}")
        if not os.path.exists(self.preproc_path):
            raise FileNotFoundError(f"V4 Preprocessor artifact not found at: {self.preproc_path}")
        if not os.path.exists(self.encoders_path):
            raise FileNotFoundError(f"V4 Target mapping artifact not found at: {self.encoders_path}")

        # Load frozen model and preprocessor
        self.model = joblib.load(self.model_path)
        self.preprocessor = PreprocessingArtifactManager.load(self.preproc_path)

        # Load target mapping
        with open(self.encoders_path, "r", encoding="utf-8") as f:
            meta = json.load(f)
        self.target_mapping = meta.get("target_mapping", {"Low": 0, "Moderate": 1, "High": 2})
        self.reverse_mapping = {int(k): v for k, v in meta.get("reverse_target_mapping", {"0": "Low", "1": "Moderate", "2": "High"}).items()}

        # Load feature engineer with V4 configuration (expanded features enabled)
        include_expanded = True
        if os.path.exists(self.config_path):
            try:
                with open(self.config_path, "r", encoding="utf-8") as f:
                    cfg = json.load(f)
                fe_cfg = cfg.get("feature_engineer_config", {})
                include_expanded = fe_cfg.get("include_expanded", True)
                self.model_version = cfg.get("candidate_version", "V4")
            except Exception:
                include_expanded = True
                
        self.feature_engineer = FeatureEngineer(include_engineered=True, include_expanded=include_expanded)

    def is_healthy(self) -> bool:
        """Checks if all required model components are loaded in memory."""
        return (
            self.model is not None and
            self.preprocessor is not None and
            self.reverse_mapping is not None and
            self.feature_engineer is not None
        )

    def predict_single(self, patient_dict: Dict[str, Any]) -> Dict[str, Any]:
        """
        Runs single patient encounter inference through the frozen V4 pipeline.
        """
        df_single = pd.DataFrame([patient_dict])
        results = self.predict_batch(df_single)
        return results[0]

    def predict_batch(self, input_data: Union[pd.DataFrame, List[Dict[str, Any]]]) -> List[Dict[str, Any]]:
        """
        Runs batch patient encounter inference through the frozen V4 pipeline.
        """
        if not self.is_healthy():
            raise RuntimeError("Inference engine artifacts are not loaded.")

        if isinstance(input_data, list):
            df_input = pd.DataFrame(input_data)
        elif isinstance(input_data, pd.DataFrame):
            df_input = input_data.copy()
        else:
            raise TypeError("Input must be a pandas DataFrame or list of dicts.")

        # 1. Feature Engineering (computes organ_impairment_index, cumulative_treatment_load, etc.)
        df_engineered = self.feature_engineer.transform(df_input)

        # 2. Preprocessing (applies frozen ColumnTransformer)
        X_proc = self.preprocessor.transform(df_engineered)

        # 3. Model Prediction (applies frozen LightGBM with conservative multipliers W=[1.0, 1.05, 1.05])
        class_preds = self.model.predict(X_proc)

        # 4. Model Probabilities (genuine probabilities from frozen base estimator)
        if hasattr(self.model, "predict_proba"):
            probs = self.model.predict_proba(X_proc)
        else:
            probs = None

        output = []
        for i, pred_idx in enumerate(class_preds):
            pred_class = self.reverse_mapping.get(int(pred_idx), "Unknown")
            
            prob_dict = {}
            if probs is not None:
                prob_row = probs[i]
                for class_idx, prob_val in enumerate(prob_row):
                    cname = self.reverse_mapping.get(class_idx, f"Class_{class_idx}")
                    prob_dict[cname] = float(round(prob_val, 4))
            else:
                prob_dict = {"Low": 0.0, "Moderate": 0.0, "High": 0.0}

            output.append({
                "predicted_toxicity_risk": pred_class,
                "probabilities": prob_dict,
                "model_version": self.model_version,
                "disclaimer": DISCLAIMER_TEXT
            })

        return output
