"""
Pydantic Schemas for Request Validation and Structured API Responses.
Role: Integration Engineer.

Strictly preserves V4 input schema and output expectations:
- Validates all 20 numerical features and 10 categorical features
- Prevents silent imputation of missing values
- Returns explicit string labels ("Low", "Moderate", "High")
- Formats probability dictionary and model version
"""

from typing import Dict, List, Optional, Any, Union
from pydantic import BaseModel, Field, field_validator


DISCLAIMER_TEXT = (
    "This prediction is generated by a research decision-support prototype "
    "and does not constitute a clinical diagnosis or treatment recommendation."
)


class PatientToxicityInput(BaseModel):
    """
    Input schema representing raw patient encounter data.
    All 30 raw predictor features are required.
    Engineered features (cumulative_treatment_load, etc.) are computed internally.
    """
    # 20 Numerical Features
    age: float = Field(..., description="Patient age in years", ge=0.0, le=125.0)
    mutation_burden: float = Field(..., description="Tumor mutational burden", ge=0.0)
    gene_expression_score: float = Field(..., description="Gene expression score", ge=0.0)
    ctdna_level: float = Field(..., description="Circulating tumor DNA level (ng/mL)", ge=0.0)
    tumor_marker_level: float = Field(..., description="Serum tumor marker level (ng/mL)", ge=0.0)
    inflammation_marker: float = Field(..., description="Inflammatory marker level (CRP/ESR)", ge=0.0)
    heart_rate: float = Field(..., description="Resting heart rate (bpm)", ge=20.0, le=260.0)
    systolic_bp: float = Field(..., description="Systolic blood pressure (mmHg)", ge=40.0, le=300.0)
    diastolic_bp: float = Field(..., description="Diastolic blood pressure (mmHg)", ge=20.0, le=200.0)
    oxygen_saturation: float = Field(..., description="Blood oxygen saturation SpO2 (%)", ge=50.0, le=100.0)
    hemoglobin: float = Field(..., description="Hemoglobin level (g/dL)", ge=1.0, le=25.0)
    white_blood_cell_count: float = Field(..., description="White blood cell count (k/uL)", ge=0.1, le=120.0)
    platelet_count: float = Field(..., description="Platelet count (k/uL)", ge=5.0, le=2000.0)
    creatinine_level: float = Field(..., description="Serum creatinine (mg/dL)", ge=0.1, le=25.0)
    liver_function_marker: float = Field(..., description="Liver function marker (ALT/AST in U/L)", ge=1.0, le=1500.0)
    drug_dose: float = Field(..., description="Administered oncology drug dose (mg)", ge=0.0)
    treatment_cycle: int = Field(..., description="Current treatment cycle number", ge=1)
    previous_treatment_count: int = Field(..., description="Number of previous treatment regimens", ge=0)
    previous_toxicity_grade: float = Field(..., description="Prior toxicity grade (0.0 to 5.0)", ge=0.0, le=5.0)
    comorbidity_count: float = Field(..., description="Count of baseline comorbidities", ge=0.0)

    # 10 Categorical Features
    sex: str = Field(..., description="Biological sex (e.g. Female, Male)")
    cancer_type: str = Field(..., description="Cancer primary site (e.g. Breast Cancer, Lung, Colorectal)")
    cancer_stage: str = Field(..., description="Cancer staging (e.g. Stage I, Stage II, Stage III, Stage IV)")
    smoking_history: str = Field(..., description="Tobacco smoking history (e.g. Never, Former, Current)")
    mutation_primary: str = Field(..., description="Primary detected mutation (e.g. EGFR, KRAS, None)")
    mutation_secondary: str = Field(..., description="Secondary detected mutation (e.g. TP53, PIK3CA, None)")
    biomarker_trend: str = Field(..., description="Biomarker trajectory (Increasing, Stable, Decreasing)")
    treatment_type: str = Field(..., description="Therapy classification (e.g. Chemotherapy, Immunotherapy, Targeted Therapy)")
    drug_name: str = Field(..., description="Oncology drug name (e.g. Erlotinib, Pembrolizumab)")
    previous_adverse_event: bool = Field(..., description="Indicator of whether patient experienced prior adverse event")

    @field_validator("previous_adverse_event", mode="before")
    @classmethod
    def parse_adverse_event(cls, value: Any) -> bool:
        """Coerce boolean strings ('true', '1', 'yes') into proper booleans."""
        if isinstance(value, bool):
            return value
        if isinstance(value, str):
            return value.strip().lower() in ("true", "1", "yes", "t", "y")
        if isinstance(value, (int, float)):
            return bool(value)
        return value

    model_config = {
        "json_schema_extra": {
            "example": {
                "age": 62.0,
                "sex": "Female",
                "cancer_type": "NSCLC",
                "cancer_stage": "Stage III",
                "smoking_history": "Former",
                "mutation_primary": "EGFR",
                "mutation_secondary": "TP53",
                "mutation_burden": 6.8,
                "gene_expression_score": 49.8,
                "ctdna_level": 1.4,
                "tumor_marker_level": 24.7,
                "inflammation_marker": 4.2,
                "biomarker_trend": "Stable",
                "heart_rate": 79.0,
                "systolic_bp": 128.0,
                "diastolic_bp": 80.0,
                "oxygen_saturation": 96.0,
                "hemoglobin": 12.5,
                "white_blood_cell_count": 7.41,
                "platelet_count": 231.0,
                "creatinine_level": 1.0,
                "liver_function_marker": 17.3,
                "treatment_type": "Targeted Therapy",
                "drug_name": "Erlotinib",
                "drug_dose": 150.0,
                "treatment_cycle": 4,
                "previous_treatment_count": 1,
                "previous_adverse_event": False,
                "previous_toxicity_grade": 0.0,
                "comorbidity_count": 1.0
            }
        }
    }


class ToxicityProbabilities(BaseModel):
    """Calibrated probability estimates for each of the three toxicity risk tiers."""
    Low: float = Field(..., description="Predicted probability of Low toxicity risk [0.0 - 1.0]")
    Moderate: float = Field(..., description="Predicted probability of Moderate toxicity risk [0.0 - 1.0]")
    High: float = Field(..., description="Predicted probability of High toxicity risk [0.0 - 1.0]")


class ToxicityPredictionResponse(BaseModel):
    """Structured response schema returned by the /predict endpoint."""
    predicted_toxicity_risk: str = Field(..., description="Predicted toxicity risk category: 'Low', 'Moderate', or 'High'")
    probabilities: ToxicityProbabilities = Field(..., description="Class probability estimates from frozen V4 model")
    model_version: str = Field("V4", description="Frozen Stage 1 ML model version identifier")
    disclaimer: str = Field(DISCLAIMER_TEXT, description="Mandatory decision-support prototype disclaimer")


class BatchToxicityPredictionResponse(BaseModel):
    """Structured response schema returned by the /predict/batch endpoint."""
    predictions: List[ToxicityPredictionResponse] = Field(..., description="List of individual prediction responses")
    total_records: int = Field(..., description="Number of records evaluated in the batch")
    model_version: str = Field("V4", description="Frozen model version identifier")


class HealthResponse(BaseModel):
    """Response schema returned by the /health endpoint."""
    status: str = Field("ok", description="Service health status")
    model_version: str = Field("V4", description="Loaded model version")
    artifacts_loaded: bool = Field(..., description="True if model, preprocessor, and encoder artifacts are loaded")
    timestamp: str = Field(..., description="Current system timestamp")
