"""
FINAL SECTION — '1 HOUR BEFORE VIVA' QUICK REVISION SHEET
Contains the concise, high-yield revision bullet points and top 25 must-know questions.
"""

REVISION_ML_POINTS = [
    "<strong>Definition:</strong> ML is algorithms learning patterns from data to make predictions without hardcoded rules.",
    "<strong>Core Paradigms:</strong> Supervised (labeled targets), Unsupervised (unlabeled structure), Reinforcement (rewards/penalties).",
    "<strong>Supervised Tasks:</strong> Classification outputs discrete classes (Low/Mod/High); Regression outputs continuous numbers.",
    "<strong>Features vs Target:</strong> Features (X) are input biomarkers/labs; Target (y) is the outcome to predict.",
    "<strong>Data Splitting:</strong> Train (fits weights), Validation (tunes hyperparameters), Test (unbiased locked audit).",
    "<strong>Patient-Level Split:</strong> Always group splits by patient_id in healthcare to prevent data leakage across multiple visits.",
    "<strong>Leakage Prevention:</strong> Preprocessing transformers (imputers, scalers) must be fitted strictly on Train and only transformed on Test.",
    "<strong>Missing Values:</strong> Use Median Imputation for skewed numeric lab values; use 'Unknown' category for categorical variables.",
    "<strong>Encoding:</strong> One-Hot Encoding for nominal variables (no order, e.g. cancer_type); Ordinal Encoding for ranked variables (e.g. stage I-IV).",
    "<strong>Feature Scaling:</strong> Standardizes feature ranges so large magnitudes (platelets) do not dominate small ones (creatinine).",
    "<strong>Normalization:</strong> Min-Max bounds values between [0, 1]; sensitive to extreme outliers.",
    "<strong>Standardization:</strong> Z-score centers values to mean=0 and std=1; preserves outlier signals robustly.",
    "<strong>Overfitting:</strong> High variance; model memorizes training noise; high train accuracy but poor test accuracy.",
    "<strong>Underfitting:</strong> High bias; model is too simple to capture patterns; poor train and poor test accuracy.",
    "<strong>Bias-Variance Tradeoff:</strong> Total error = Bias² + Variance + Irreducible error. Optimal model balances both.",
    "<strong>Tree Invariance:</strong> Tree-based algorithms (Decision Trees, Random Forest, LightGBM) are scale-invariant.",
    "<strong>Random Forest:</strong> Bagging ensemble of decorrelated decision trees; reduces variance by averaging tree votes.",
    "<strong>Gradient Boosting (LightGBM):</strong> Trains trees sequentially, where each new tree corrects the residual errors of preceding trees.",
    "<strong>Our Champion Model:</strong> Candidate V4 (regularized LightGBM with learning_rate=0.05, max_depth=5).",
    "<strong>Parameters vs Hyperparameters:</strong> Parameters are learned internally (weights, splits); Hyperparameters are tuned externally.",
    "<strong>Cross-Validation:</strong> 5-Fold Stratified Group CV ensures balanced class proportions and 0% patient leakage across folds.",
    "<strong>ML Pipeline:</strong> Bundles imputation, scaling, and model into an atomic, reproducible artifact (pipeline.joblib).",
    "<strong>Accuracy:</strong> (TP + TN) / Total. Misleading and dangerous on imbalanced clinical datasets.",
    "<strong>Precision:</strong> TP / (TP + FP). Measures positive predictive value; minimizes false alarms.",
    "<strong>Recall (Sensitivity):</strong> TP / (TP + FN). Measures ability to catch positive cases; primary clinical safety metric.",
    "<strong>F1-Score:</strong> Harmonic mean of Precision and Recall: 2 * (P * R) / (P + R).",
    "<strong>Macro F1:</strong> Computes F1 independently for each class and averages them, giving equal weight to minority classes.",
    "<strong>Confusion Matrix:</strong> 2D grid comparing predicted classes against actual classes to reveal exact error distributions.",
    "<strong>Regression Metrics:</strong> MAE is average absolute error; RMSE penalizes large outlier errors heavily; R² is variance explained.",
    "<strong>Clinical Safety Priority:</strong> In oncology toxicity, a False Negative (missing high risk) is far more dangerous than a False Positive."
]

REVISION_DL_POINTS = [
    "<strong>Definition:</strong> Deep Learning uses multi-layered neural networks to automatically learn representations from raw data.",
    "<strong>ML vs DL:</strong> ML uses manual features on tabular data; DL uses automatic representation learning on raw images/sequences.",
    "<strong>Perceptron:</strong> Mathematical node computing y = σ(WᵀX + b), where W is weight, b is bias, and σ is activation.",
    "<strong>Weights & Bias:</strong> Weights control connection strength/slope; Bias shifts the activation threshold intercept.",
    "<strong>Activation Functions:</strong> Introduce non-linearity; without them, multi-layer networks collapse to a single linear equation.",
    "<strong>ReLU:</strong> f(x) = max(0, x). Standard for hidden layers; avoids vanishing gradients and computes fast.",
    "<strong>Sigmoid:</strong> Squeezes inputs to (0, 1); used for binary classification outputs; saturates at extremes.",
    "<strong>Tanh:</strong> Squeezes inputs to (-1, 1); zero-centered; commonly used inside LSTM recurrent cells.",
    "<strong>Softmax:</strong> Converts raw logits into normalized probabilities summing to 1.0; standard for multi-class outputs.",
    "<strong>Forward Pass:</strong> Passes inputs through layers to compute predictions and loss. No weight updates occur here.",
    "<strong>Loss Function:</strong> Measures discrepancy between prediction and target (Cross-Entropy for classification, MSE for regression).",
    "<strong>Backpropagation:</strong> Uses calculus chain rule backward from output to compute gradients ∂Loss/∂Weight for all parameters.",
    "<strong>Gradient Descent:</strong> Iterative optimizer updating weights: W_new = W_old - α * ∇Loss.",
    "<strong>Learning Rate (α):</strong> Controls update step size; too large diverges, too small converges excessively slowly.",
    "<strong>Epoch:</strong> One complete pass of the entire training dataset forward and backward through the network.",
    "<strong>Batch:</strong> Subset of samples processed concurrently before a weight update (typically 16, 32, 64).",
    "<strong>Iteration:</strong> A single weight update step: Iterations per Epoch = Total Samples / Batch Size.",
    "<strong>Adam Optimizer:</strong> Combines Momentum (moving average of gradients) and RMSProp (adaptive per-weight learning rates).",
    "<strong>Training Loop:</strong> 1. Load batch &rarr; 2. Forward pass &rarr; 3. Loss &rarr; 4. Backprop &rarr; 5. Optimizer step.",
    "<strong>DL Overfitting:</strong> Diagnosed when training loss decreases while validation loss starts rising.",
    "<strong>Dropout:</strong> Randomly disables a fraction of neurons during training to prevent co-adaptation; disabled during test time.",
    "<strong>L2 Regularization:</strong> Weight decay adds λΣ(W²) penalty to loss, shrinking weights to produce smoother boundaries.",
    "<strong>Early Stopping:</strong> Automatically halts training when validation loss stops improving for N epochs (patience).",
    "<strong>CNN:</strong> Designed for grid data (images); uses learnable filters for local feature extraction and parameter sharing.",
    "<strong>Max Pooling:</strong> Downsamples feature maps by taking max value in window, halving dimensions and providing spatial invariance.",
    "<strong>Our Stage 2 CNN:</strong> Classifies 224x224 RGB digital pathology tiles into Benign, Malignant, or Inflammation.",
    "<strong>RNN:</strong> Sequential network with recurrent feedback loops; suffers from vanishing gradients on long sequences.",
    "<strong>LSTM:</strong> Solves vanishing gradients using a persistent Cell State regulated by Forget, Input, and Output gates.",
    "<strong>Transformers:</strong> Process entire sequences in parallel using Self-Attention (Query, Key, Value), replacing recurrent bottlenecks.",
    "<strong>Multimodal Fusion:</strong> Combining vision CNN scores + temporal LSTM scores into a unified clinical alert tier."
]

REVISION_EDA_POINTS = [
    "EDA is the exploratory investigation of data distributions, correlations, and anomalies before model development.",
    "Always check data types, missing values percentage, and duplicate records first.",
    "Target distribution check: In our project, 42% Low, 36% Moderate, 22% High risk encounters (class imbalance).",
    "Univariate analysis examines one feature at a time using histograms and KDE density curves.",
    "Right-skewed variables (e.g., creatinine, liver enzymes) have long right tails and should be summarized by median, not mean.",
    "Bivariate analysis investigates feature-target relationships using box plots (numeric vs categorical) or cross-tabs.",
    "Multivariate analysis uses correlation heatmaps and pairplots to detect multi-collinearity across biomarkers.",
    "Pearson correlation measures strict linear relationships; Spearman correlation measures monotonic rank relationships.",
    "Outliers can be detected using the IQR rule: values outside [Q1 - 1.5*IQR, Q3 + 1.5*IQR].",
    "Z-score outlier detection flags observations with absolute Z-score > 3 in approximately Gaussian features.",
    "Never blindly delete clinical outliers: in oncology, an extreme lab value often represents acute organ failure.",
    "Check for feature correlation with patient_id: if correlation is non-zero, it indicates severe data collection bias.",
    "Visualizing distributions between train and test splits verifies that both sets represent the same patient population.",
    "Missingness heatmaps identify whether data is missing at random or systematically absent in certain cancer types.",
    "Key project finding: Elevated creatinine and high drug doses correlated strongly with High Toxicity Risk."
]

REVISION_ROLE_POINTS = {
    "de": [
        "Data Engineer builds automated data pipelines, ETL/ELT workflows, and scalable databases.",
        "Responsible for raw clinical data ingestion from hospital EHRs, labs, and pathology image servers.",
        "Implements strict schema validation using Pydantic to reject corrupted records.",
        "Performs data deduplication, unit standardization (e.g., g/dL), and type casting.",
        "Implements patient-level splitting (700 Train / 150 Val / 150 Test) to enforce 0% patient leakage.",
        "Produces clean, versioned datasets: master_patient_dataset.csv and tile image directories.",
        "Handles storage architecture: SQL databases for relational encounters, S3/MinIO for whole slide images.",
        "Enforces training-only data augmentation and temporal forecast window partitioning.",
        "Key Tools: Python, Pandas, Polars, SQL, Pydantic, Apache Spark, Airflow, Docker, PostgreSQL.",
        "Viva Core: 'I build the reliable data plumbing that transforms raw clinical chaos into clean, validated data.'"
    ],
    "mle": [
        "ML Engineer bridges data science prototypes and robust production machine learning systems.",
        "Designs reproducible end-to-end training pipelines bundling preprocessing and estimators.",
        "Benchmarks multiple candidate algorithms (Logistic Regression, Random Forest, LightGBM).",
        "Tunes hyperparameters (learning_rate, max_depth, n_estimators) using Stratified Group Cross-Validation.",
        "Selects Champion Model: Candidate V4 (regularized LightGBM with conservative decision rules).",
        "Freezes and serializes trained models into deployable artifacts (model.joblib, preprocessor.joblib).",
        "Optimizes training throughput, GPU memory allocation, and vectorization.",
        "Collaborates with Data Engineers on feature pipelines and with Integration Engineers on APIs.",
        "Monitors production models for data drift (covariate shift) and concept drift.",
        "Viva Core: 'I build reproducible training pipelines and optimize production-grade model artifacts.'"
    ],
    "eval": [
        "Evaluation Engineer acts as an independent auditor of model quality and clinical safety.",
        "Maintains complete separation of duties from the ML Engineer to prevent developer confirmation bias.",
        "Holds exclusive custody of the locked test set (1,750 encounters across 1,200 patients).",
        "Evaluates domain-appropriate metrics: Macro F1 (0.5288) and High-Risk Safety Recall (0.6287).",
        "Calculates 95% Bootstrap Confidence Intervals (1,000 resamples) to prove statistical stability.",
        "Performs subgroup analysis across 26 clinical and demographic cohorts to guarantee fairness.",
        "Dissects confusion matrices to perform error transition analysis on high-risk false negatives.",
        "Verifies that test performance aligns with validation benchmarks without hidden failure modes.",
        "Authorizes model readiness before the system can be deployed to clinical integration.",
        "Viva Core: 'I independently stress-test frozen models on locked data to certify safety and fairness.'"
    ],
    "integ": [
        "Integration Engineer embeds trained ML/DL models into hospital IT and clinical software systems.",
        "Builds high-speed RESTful microservices using FastAPI with endpoints: /health, /predict, /predict/batch.",
        "Enforces Pydantic request and response schemas to guarantee type safety and prevent runtime crashes.",
        "Implements Multimodal Late Fusion: combines CNN pathology + LSTM ctDNA + Stage 1 toxicity risk.",
        "Calculates unified clinical alert tiers (SAFE, MONITOR, CRITICAL) for oncologist decision support.",
        "Integrates backend microservices with frontend clinical dashboards (dashboard.html).",
        "Optimizes inference latency to achieve sub-15ms single-encounter response times.",
        "Writes automated integration test suites (40 passing tests using PyTest) covering APIs and edge cases.",
        "Containerizes services using Docker and configures reverse proxies and caching.",
        "Viva Core: 'I bridge models to doctors via high-speed APIs, late fusion engines, and clinical dashboards.'"
    ]
}

TOP_25_MUST_KNOW_QUESTIONS = [
    ("1. What is your project title and what problem does it solve?",
     "Personalized Precision Medicine for Oncology Treatment Optimization. It uses ML to predict chemotherapy toxicity risk (Low/Mod/High) and DL to forecast tumor progression from pathology tiles and serial ctDNA, helping oncologists deliver safer treatments."),
    ("2. What ML algorithm did you finalize for Stage 1 and why?",
     "Candidate V4: Regularized LightGBM. It excels on structured tabular clinical data, handles mixed feature types, resists skewed outliers, trains fast, and provides clear clinical feature importance."),
    ("3. What were the key evaluation scores of Candidate V4?",
     "Macro F1 = 0.5288 [95% CI: 0.5035, 0.5521], High-Risk Safety Recall = 0.6287 [95% CI: 0.5759, 0.6783], and overall Accuracy = 0.5766 on the locked test set."),
    ("4. Why is Recall more important than Accuracy in cancer toxicity prediction?",
     "A False Negative (missing a high-risk patient) can cause fatal unmonitored chemotherapy toxicity or organ failure. High Recall ensures virtually all vulnerable patients receive protective clinical monitoring."),
    ("5. How did you prevent data leakage in your project?",
     "We implemented strict Patient-Level Splitting (by patient_id) so no patient appeared in both train and test sets, and fitted all preprocessing imputers/scalers strictly on training data."),
    ("6. How did you handle missing values in lab biomarkers?",
     "We used Median Imputation for skewed numeric lab tests (robust against extreme outliers) and assigned 'Unknown' to categorical variables like smoking history and cancer type."),
    ("7. What is the difference between Normalization and Standardization?",
     "Normalization rescales values to [0, 1] (used for image pixels); Standardization centers values to mean=0 and std=1 (used for clinical lab biomarkers)."),
    ("8. What is Overfitting and how do you prevent it in ML and DL?",
     "Overfitting is memorizing training noise. In ML, prevent it using tree pruning, max_depth limits, and L2 regularization. In DL, prevent it using Dropout, Data Augmentation, and Early Stopping."),
    ("9. Explain the Bias-Variance tradeoff.",
     "Bias is underfitting from overly simplistic assumptions; Variance is overfitting from excessive model sensitivity to training noise. Optimal models balance both to minimize total test error."),
    ("10. What is K-Fold Cross-Validation and which variant did you use?",
     "We used 5-Fold Stratified Group K-Fold Cross-Validation, preserving class proportions (Stratified) and keeping all encounters of any patient together in the same fold (Group)."),
    ("11. What is an ML Pipeline?",
     "An automated Scikit-Learn pipeline bundling preprocessing (imputers, scalers, encoders) and the model estimator into an atomic object that executes identically during training and production."),
    ("12. What is an Artificial Neuron and write its formula?",
     "The basic computational unit: y = σ(Σ wᵢxᵢ + b) = σ(WᵀX + b), where W is weight, X is input, b is bias, and σ is the non-linear activation function."),
    ("13. What is ReLU and why is it preferred over Sigmoid in hidden layers?",
     "ReLU is max(0, x). It avoids vanishing gradients for positive inputs, computes fast, and speeds up convergence, whereas Sigmoid saturates at 0 and 1 with tiny derivatives."),
    ("14. What does Backpropagation do in neural networks?",
     "It calculates the partial derivatives (gradients) of the loss function with respect to all trainable weights using the calculus chain rule, propagating errors backward."),
    ("15. How does the Adam Optimizer work?",
     "Adam adapts learning rates for each parameter individually by combining Momentum (tracking past gradient velocity) and RMSProp (tracking past squared gradients)."),
    ("16. What is Dropout and when is it turned off?",
     "Dropout randomly deactivates a fraction of neurons during training to prevent co-adaptation. It is always turned off during inference/test time."),
    ("17. Why do we use CNNs for pathology images instead of standard MLPs?",
     "CNNs preserve 2D spatial relationships, use parameter sharing with small sliding filters, reduce parameter counts, and achieve translation invariance via pooling."),
    ("18. How does an LSTM solve the vanishing gradient problem in RNNs?",
     "It uses a constant error carousel (Cell State) controlled by three multiplicative gates (Forget, Input, Output) allowing gradients to flow across long time series without vanishing."),
    ("19. What is Multimodal Late Fusion in your project?",
     "Processing 2D pathology tiles through a CNN and 1D longitudinal ctDNA through an LSTM independently, then fusing their output risk scores into a composite clinical alert tier."),
    ("20. What does the Data Engineer do in your project?",
     "Builds data pipelines, validates schemas with Pydantic, handles imputation, and enforces patient-level zero-leakage splits to deliver master_patient_dataset.csv."),
    ("21. What does the EDA Engineer do in your project?",
     "Analyzes distributions, identifies skewed biomarkers, detects outliers via IQR, and generates correlation heatmaps to understand feature-target relationships before modeling."),
    ("22. What does the ML Engineer do vs a Data Scientist?",
     "Data Scientists explore data and prototype models in notebooks; ML Engineers optimize code, build reproducible pipelines, tune hyperparameters, and package model.joblib for production."),
    ("23. What does the Evaluation Engineer do and why are they separate?",
     "They independently audit frozen models on locked test data, computing 95% bootstrap CIs and 26-cohort subgroup metrics to guarantee clinical safety without developer bias."),
    ("24. What does the Integration Engineer do in your project?",
     "Deploys models via a FastAPI REST service (/predict, /health), validates JSON inputs with Pydantic, fuses multimodal scores, and renders real-time alerts on a clinical dashboard."),
    ("25. What is the clinical status and disclaimer of your AI system?",
     "It is a machine learning research decision-support prototype. It assists oncologists in risk stratification, but does not provide autonomous medical diagnosis or treatment prescriptions.")
]
