"""
Inference & Prediction Module for Stage 1 ML Toxicity Risk Prediction.
"""

import os
import json
from typing import Dict, Any, Union, List
import joblib
import pandas as pd
import numpy as np

from feature_engineering import FeatureEngineer
from preprocessing import PreprocessingArtifactManager

# Paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_PATH = os.path.join(BASE_DIR, "models", "best_model", "model.joblib")
PREPROC_PATH = os.path.join(BASE_DIR, "artifacts", "preprocessor", "preprocessor.joblib")
ENCODERS_PATH = os.path.join(BASE_DIR, "artifacts", "encoders", "target_mapping.json")

DISCLAIMER_TEXT = (
    "This prediction is generated by a research decision-support prototype "
    "and does not constitute a clinical diagnosis or treatment recommendation."
)


class ToxicityRiskPredictor:
    """
    Production-ready prediction engine that loads fitted artifacts and performs end-to-end inference.
    """
    def __init__(
        self,
        model_path: str = MODEL_PATH,
        preproc_path: str = PREPROC_PATH,
        encoders_path: str = ENCODERS_PATH
    ):
        self.model_path = os.path.abspath(model_path)
        self.preproc_path = os.path.abspath(preproc_path)
        self.encoders_path = os.path.abspath(encoders_path)
        
        self._load_artifacts()

    def _load_artifacts(self):
        if not os.path.exists(self.model_path):
            raise FileNotFoundError(f"Model file not found at: {self.model_path}")
        if not os.path.exists(self.preproc_path):
            raise FileNotFoundError(f"Preprocessor file not found at: {self.preproc_path}")
        if not os.path.exists(self.encoders_path):
            raise FileNotFoundError(f"Encoders file not found at: {self.encoders_path}")
            
        self.model = joblib.load(self.model_path)
        self.preproc_manager = PreprocessingArtifactManager.load(self.preproc_path)
        
        with open(self.encoders_path, "r") as f:
            meta = json.load(f)
            
        self.target_mapping = meta["target_mapping"]
        self.reverse_mapping = {int(k): v for k, v in meta["reverse_target_mapping"].items()}
        self.numerical_features = meta["numerical_features"]
        self.categorical_features = meta["categorical_features"]
        
        self.feature_engineer = FeatureEngineer(include_engineered=True)

    def predict_single(self, patient_dict: Dict[str, Any]) -> Dict[str, Any]:
        """
        Predicts toxicity risk for a single patient record dictionary.
        """
        df_input = pd.DataFrame([patient_dict])
        results = self.predict_batch(df_input)
        return results[0]

    def predict_batch(self, input_data: Union[pd.DataFrame, List[Dict[str, Any]]]) -> List[Dict[str, Any]]:
        """
        Predicts toxicity risk for a batch of patient records.
        """
        if isinstance(input_data, list):
            df_input = pd.DataFrame(input_data)
        elif isinstance(input_data, pd.DataFrame):
            df_input = input_data.copy()
        else:
            raise TypeError("Input data must be a pandas DataFrame or a list of dictionaries.")
            
        # Apply feature engineering
        df_engineered = self.feature_engineer.transform(df_input)
        
        # Transform via preprocessing manager
        X_transformed = self.preproc_manager.transform(df_engineered)
        
        # Predict class labels
        preds = self.model.predict(X_transformed)
        
        # Predict class probabilities if available
        if hasattr(self.model, "predict_proba"):
            probs = self.model.predict_proba(X_transformed)
        else:
            probs = None
            
        output = []
        for i, pred_idx in enumerate(preds):
            pred_class = self.reverse_mapping.get(int(pred_idx), "Unknown")
            
            prob_dict = {}
            if probs is not None:
                prob_row = probs[i]
                for class_idx, prob_val in enumerate(prob_row):
                    cname = self.reverse_mapping.get(class_idx, f"Class_{class_idx}")
                    prob_dict[cname] = float(round(prob_val, 4))
            else:
                prob_dict = {"Low": None, "Moderate": None, "High": None}
                
            res = {
                "predicted_risk": pred_class,
                "probabilities": prob_dict,
                "disclaimer": DISCLAIMER_TEXT
            }
            output.append(res)
            
        return output


def predict_patient_toxicity(patient_data: Union[Dict[str, Any], pd.DataFrame]) -> Union[Dict[str, Any], List[Dict[str, Any]]]:
    """
    Convenience wrapper function for predicting patient toxicity risk.
    """
    predictor = ToxicityRiskPredictor()
    if isinstance(patient_data, dict):
        return predictor.predict_single(patient_data)
    else:
        return predictor.predict_batch(patient_data)


if __name__ == "__main__":
    # Quick sanity check with sample patient input
    sample_patient = {
        "age": 65.0,
        "sex": "Female",
        "cancer_type": "NSCLC",
        "cancer_stage": "Stage III",
        "smoking_history": "Former",
        "mutation_primary": "EGFR",
        "mutation_secondary": "TP53",
        "mutation_burden": 8.5,
        "gene_expression_score": 52.0,
        "ctdna_level": 2.1,
        "tumor_marker_level": 30.0,
        "inflammation_marker": 5.2,
        "biomarker_trend": "Increasing",
        "heart_rate": 82.0,
        "systolic_bp": 135.0,
        "diastolic_bp": 85.0,
        "oxygen_saturation": 95.0,
        "hemoglobin": 10.5,
        "white_blood_cell_count": 8.2,
        "platelet_count": 140.0,
        "creatinine_level": 1.2,
        "liver_function_marker": 22.0,
        "treatment_type": "Targeted Therapy",
        "drug_name": "Erlotinib",
        "drug_dose": 150.0,
        "treatment_cycle": 3,
        "previous_treatment_count": 2,
        "previous_adverse_event": True,
        "previous_toxicity_grade": 2.0,
        "comorbidity_count": 2.0
    }
    
    print("Testing sample inference...")
    res = predict_patient_toxicity(sample_patient)
    print(json.dumps(res, indent=2))
