"use client";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { factors, roc, trend } from "@/lib/demo-data";

export function RiskRing({ value, tone = "#ef4e62", label = "High risk" }: { value: number; tone?: string; label?: string }) {
  const data = [{ value }, { value: 100 - value }];
  return <div className="risk-ring" role="img" aria-label={`${value} percent ${label}`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" startAngle={90} endAngle={-270} innerRadius="76%" outerRadius="94%" stroke="none"><Cell fill={tone} /><Cell fill="#e8edf5" /></Pie></PieChart></ResponsiveContainer><div><strong>{value}%</strong><span>{label}</span></div></div>;
}
export function FactorBars() { return <div className="chart-wrap" role="img" aria-label="Top toxicity contributors led by creatinine at 24 percent"><ResponsiveContainer width="100%" height={220}><BarChart data={factors} layout="vertical" margin={{ left: 8, right: 20 }}><XAxis type="number" hide domain={[0, 30]} /><YAxis type="category" dataKey="name" width={86} tickLine={false} axisLine={false} /><Tooltip formatter={(v) => `${v}%`} /><Bar dataKey="value" fill="#2f7df4" radius={[0, 5, 5, 0]} barSize={13} /></BarChart></ResponsiveContainer></div> }
export function TrendChart() { return <div className="chart-wrap" role="img" aria-label="ctDNA and CEA values rise between January and June"><ResponsiveContainer width="100%" height={240}><AreaChart data={trend}><defs><linearGradient id="ct" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#5e6cff" stopOpacity=".28" /><stop offset="1" stopColor="#5e6cff" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="#e8edf5" vertical={false} /><XAxis dataKey="m" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Tooltip /><Area type="monotone" dataKey="ctDNA" stroke="#5e6cff" fill="url(#ct)" strokeWidth={3} /><Line type="monotone" dataKey="CEA" stroke="#ef4e62" strokeWidth={2} /></AreaChart></ResponsiveContainer></div> }
export function RocChart() { return <div className="chart-wrap" role="img" aria-label="ROC curves for ML, DL and NLP models"><ResponsiveContainer width="100%" height={250}><LineChart data={roc}><CartesianGrid stroke="#e8edf5" /><XAxis dataKey="x" /><YAxis /><Tooltip /><Line type="monotone" dataKey="ML" stroke="#2f7df4" dot={false} strokeWidth={2} /><Line type="monotone" dataKey="DL" stroke="#7657ed" dot={false} strokeWidth={2} /><Line type="monotone" dataKey="NLP" stroke="#06a6b7" dot={false} strokeWidth={2} /></LineChart></ResponsiveContainer></div> }
