"use client";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { factors, roc, trend } from "@/lib/demo-data";

export function RiskRing({ value, tone = "#ef4e62", label = "High risk" }: { value: number; tone?: string; label?: string }) {
  const data = [{ value }, { value: 100 - value }];
  return <div className="risk-ring" role="img" aria-label={`${value} percent ${label}`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" startAngle={90} endAngle={-270} innerRadius="76%" outerRadius="94%" stroke="none"><Cell fill={tone} /><Cell fill="#25313a" /></Pie></PieChart></ResponsiveContainer><div><strong>{value}%</strong><span>{label}</span></div></div>;
}
const tooltipStyle = { background: "#111a22", border: "1px solid #34414b", borderRadius: 8, color: "#f5f2ea", fontSize: 11 };
const axisTick = { fill: "#7f8e98", fontSize: 10 };
export function FactorBars() { return <div className="chart-wrap" role="img" aria-label="Top toxicity contributors led by creatinine at 24 percent"><ResponsiveContainer width="100%" height={220}><BarChart data={factors} layout="vertical" margin={{ left: 8, right: 20 }}><XAxis type="number" hide domain={[0, 30]} /><YAxis type="category" dataKey="name" width={86} tickLine={false} axisLine={false} tick={axisTick} /><Tooltip contentStyle={tooltipStyle} formatter={(v) => `${v}%`} /><Bar dataKey="value" fill="#d9a85f" radius={[0, 5, 5, 0]} barSize={13} /></BarChart></ResponsiveContainer></div> }
export function TrendChart() { return <div className="chart-wrap" role="img" aria-label="ctDNA and CEA values rise between January and June"><ResponsiveContainer width="100%" height={240}><AreaChart data={trend}><defs><linearGradient id="ct" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#8b7cf6" stopOpacity=".3" /><stop offset="1" stopColor="#8b7cf6" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="#26323b" vertical={false} /><XAxis dataKey="m" axisLine={false} tickLine={false} tick={axisTick} /><YAxis axisLine={false} tickLine={false} tick={axisTick} /><Tooltip contentStyle={tooltipStyle} /><Area type="monotone" dataKey="ctDNA" stroke="#8b7cf6" fill="url(#ct)" strokeWidth={3} /><Line type="monotone" dataKey="CEA" stroke="#f16d78" strokeWidth={2} /></AreaChart></ResponsiveContainer></div> }
export function RocChart() { return <div className="chart-wrap" role="img" aria-label="ROC curves for ML, DL and NLP models"><ResponsiveContainer width="100%" height={250}><LineChart data={roc}><CartesianGrid stroke="#26323b" /><XAxis dataKey="x" tick={axisTick} /><YAxis tick={axisTick} /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="ML" stroke="#d9a85f" dot={false} strokeWidth={2} /><Line type="monotone" dataKey="DL" stroke="#8b7cf6" dot={false} strokeWidth={2} /><Line type="monotone" dataKey="NLP" stroke="#59d7e8" dot={false} strokeWidth={2} /></LineChart></ResponsiveContainer></div> }
